name: test1
run-name: test2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkout-build-scan-action:
    runs-on: ubuntu-latest

    permissions:
      statuses: write
      pull-requests: write
      # The next 3 permissions are used for SARIF report upload
      security-events: write
      actions: read
      contents: read

    steps:
      # Need to check out data before we can do anything
      - uses: actions/checkout@v4

      # Use the rl-scanner-cloud-composite action
      - name: Scan build artifact on the Portal
        id: rl-scan
        env:
          RLPORTAL_ACCESS_TOKEN: ${{ secrets.RLPORTAL_ACCESS_TOKEN }}
        uses: maarten-boot/test-gh-action-rl-scanner-cloud-composite-test@v1.0.1
        with:
          rl-verbose: true
          rl-portal-server: test
          rl-portal-org: Test
          rl-portal-group: Default
          rl-timeout: 20
          rl-submit-only: false
          artifact-to-scan: README.md
          report-path: MyReportsDirectory
          rl-package-url: my-project/my-package@1.0
