name: ReversingLabs rl-scanner-cloud only
run-name: rl-scanner-cloud-only

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkout-build-scan-only:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      pull-requests: write

    steps:
      # Need to check out data before we can do anything
      - uses: actions/checkout@v4

      # Use the rl-scanner-cloud-only action
      - name: Scan build artifact on the Portal
        id: rl-scan
        env:
          RLPORTAL_ACCESS_TOKEN: ${{ secrets.RLPORTAL_ACCESS_TOKEN }}
        uses: reversinglabs/gh-action-rl-scanner-cloud-only@v1
        with:
          artifact-to-scan: README.md
          rl-verbose: true
          rl-portal-server: test
          rl-portal-org: Test
          rl-portal-group: Default
          rl-package-url: my-project/my-package@1.0

      - name: report the scan status
        if: success() || failure()
        run: |
          echo "The status is: '${{ steps.rl-scan.outputs.status }}'"
          echo "The description is: '${{ steps.rl-scan.outputs.description }}'"
